import type { Content } from "./types";
import { code } from "./code";

export const zh: Content = {
  meta: {
    title: "tingly-ssh：换网不断线的 SSH",
    description: "Wi-Fi 切 5G、合上盖子、地铁进隧道，还是原来那条 ssh 会话，输出一行不丢。不改 OpenSSH，不改 sshd。",
  },
  nav: { demo: "演示", how: "原理", compare: "对比", start: "快速上手", faq: "常见问题", github: "GitHub" },
  hero: {
    eyebrow: "SSH over QUIC，带会话恢复",
    title: "你的 SSH，",
    titleAccent: "不会再断了。",
    lead: "Wi-Fi 切 5G、合上盖子、地铁进隧道，还是原来那条 ssh 会话，接着往下跑，每个字节的输出都会送达。",
    ctaPrimary: "开始使用",
    ctaSecondary: "看演示",
    install: "两端各一个二进制 · Linux 与 macOS · MPL-2.0",
    art: {
      sending: "正在发送",
      outage: "网络消失 · 数据留在服务端",
      replay: "恢复联网 · 补发缺口",
      done: "每个字节按序送达，不重不漏",
    },
  },
  intro: {
    paragraphs: [
      "SSH 是为不挪窝的机器设计的。一条会话就是两个固定地址之间的一条 TCP 连接，笔记本的地址一变，或者网络消失半分钟，连接就没了。它上面跑着的任务，以及你离开期间它打印的输出，也跟着没了。",
      "tingly-ssh 在两端各放一个小 bridge，用 QUIC 承载你的 SSH 连接，上面再加一层可以恢复的会话层。地址可以变，网络可以断；等网络回来，还是原来那条 ssh 会话，接着往下跑，每个字节的输出都会送达。",
      "SSH 本身什么都不用改。你的密钥、sshd、~/.ssh/config，以及所有说 SSH 的工具：scp、rsync、git、端口转发、tmux，都照旧。",
    ],
    facts: ["不改 OpenSSH 与 sshd", "复用你已有的 SSH 密钥", "每个字节按序送达，不重不漏"],
  },
  demo: {
    title: "看一条连接怎么活下来",
    lead: "同一台笔记本，同一台服务器，两个终端跑同一个长任务。左边是普通 ssh，右边是同一条 ssh 走 tingly-ssh。两边经历的是同一次 IP 变化，以及随后 15 秒的彻底断网。",
    left: "普通 ssh",
    right: "ssh + tingly-ssh",
    chapters: { start: "开始", switch: "IP 变化", outage: "网络消失", back: "恢复联网" },
    note: "这是真实录制，不是动画。\"笔记本\"是一个 Linux 网络命名空间，它的地址真的变了，链路也真的断了。左边的任务进度卡住，ssh 随后放弃；右边的进度停一下，追上来，然后跑完。录制脚本会检查 150 次进度更新是否全部按顺序、不重不漏地到达终端，否则录制失败。",
    reproduce: "自己复现：demo/record.sh",
    quote: {
      text: "150 次进度更新，150 次到达终端，按顺序，不重不漏。",
      cite: "demo/record.sh 每次录制都会做这项检查，不通过则录制失败",
    },
  },
  fit: {
    title: "适合你吗？",
    yesTitle: "适合，如果你",
    yes: [
      "用笔记本在家、公司、咖啡店、手机热点之间来回切",
      "常通过 SSH 跑长编译、数据迁移、训练任务，受够了守着连接",
      "开着 ssh -L 隧道连数据库、Jupyter 或内网面板，Wi-Fi 一断它们就一起断",
      "经常在高铁、飞机或移动网络上，网络时不时消失 10 到 60 秒",
      "想要这些，但不想上 VPN、托管控制面或新的身份系统",
    ],
    noTitle: "可能不适合，如果你",
    no: [
      "需要会话扛过任意一端机器重启：会话状态在内存里",
      "用 Windows：目前只支持 Linux 和 macOS",
      "所在网络封 UDP：TCP 兜底在路线图里",
      "主要在极高延迟的链路上敲命令：这时 mosh 的本地回显更合适",
    ],
  },
  how: {
    title: "工作原理",
    lead: "两端各放一个小 bridge，用 QUIC 承载你的 SSH 连接，上面再加一层可恢复会话层。认证和端到端加密仍然由 SSH 负责，隧道看不到 SSH 流里的内容。",
    laptop: "笔记本",
    server: "服务器 · sshd",
    delivered: "已送达",
    buffer: "重放缓冲",
    lost: "在线路上丢失",
    phases: {
      normal: { label: "正常", caption: "输出从 sshd 流向你的终端。服务端会保留每一块数据，直到笔记本确认收到。" },
      switch: { label: "IP 变化", caption: "Wi-Fi 切 5G，笔记本的地址变了。QUIC 把连接迁移到新路径上，数据包继续流动。" },
      outage: { label: "网络消失", caption: "彻底没网。在路上的数据块丢在了线路上，新的输出在重放缓冲里排队。sshd 毫无察觉。" },
      resume: { label: "恢复", caption: "新链路建立。两端先对齐字节偏移量，再只重放缺的那部分：没有缺口，也没有重复。" },
    },
    play: "播放",
    pause: "暂停",
    points: [
      { title: "地址变化", body: "Wi-Fi 切 5G、NAT 重绑定，都交给 QUIC 的连接迁移处理，通常你察觉不到。" },
      { title: "断网", body: "会话层保留尚未确认的字节。重连后交换偏移量，重放缺失部分。默认可恢复 60 秒，可以调。" },
      { title: "SSH 那边什么都没变", body: "里面跑的就是原样的 SSH 协议。sshd、你的密钥、known_hosts 和 ssh 的每个功能都保持原样。" },
    ],
  },
  compare: {
    title: "和其他方案比",
    lead: "如实列出取舍。tmux 是搭档，不是对手：隧道负责让连接活着，万一连接真断了，由 tmux 保住正在做的事。",
    tools: ["tingly-ssh", "mosh", "Eternal Terminal", "autossh", "只用 tmux"],
    rows: [
      { label: "IP 变了还能用", cells: [{ v: "yes" }, { v: "yes" }, { v: "yes" }, { v: "no", note: "新会话" }, { v: "no", note: "手动 reattach" }] },
      { label: "短时断网能恢复", cells: [{ v: "yes", note: "默认 60 秒" }, { v: "yes" }, { v: "yes" }, { v: "no", note: "新会话" }, { v: "no", note: "手动 reattach" }] },
      { label: "输出逐字节送达", cells: [{ v: "yes" }, { v: "no", note: "只同步最新一屏" }, { v: "yes" }, { v: "no" }, { v: "yes", note: "在 pane 里" }] },
      { label: "scp、sftp、rsync、SSH 上的 git", cells: [{ v: "yes" }, { v: "no" }, { v: "no" }, { v: "yes" }, { v: "yes" }] },
      { label: "-L / -R / -D 与 agent 转发", cells: [{ v: "yes" }, { v: "no" }, { v: "partial" }, { v: "yes" }, { v: "yes" }] },
      { label: "终端原生回滚", cells: [{ v: "yes" }, { v: "no" }, { v: "yes" }, { v: "yes" }, { v: "yes" }] },
      { label: "sshd 与 SSH 认证不变", cells: [{ v: "yes" }, { v: "yes" }, { v: "yes" }, { v: "yes" }, { v: "yes" }] },
      { label: "服务端无需额外组件", cells: [{ v: "no", note: "1 个进程、1 个 UDP 端口" }, { v: "no", note: "UDP 60000+" }, { v: "no", note: "etserver" }, { v: "yes" }, { v: "yes" }] },
      { label: "慢链路上的输入预测", cells: [{ v: "no" }, { v: "yes" }, { v: "no" }, { v: "no" }, { v: "no" }] },
    ],
    footnote: "为什么用 QUIC，而不是 MPTCP 或 WireGuard：见文档里的 ADR-0001。",
  },
  start: {
    title: "快速上手",
    lead: "大约五分钟。需要：Linux / macOS 客户端，一台跑着 sshd 的服务器，以及一个能放行的 UDP 端口。",
    steps: [
      { title: "两端都装上", body: "每个 release 都附带 linux/darwin × amd64/arm64 的预编译包。", code: code.install, codeLabel: "shell", after: `也可以用 Go 1.26+：${code.goInstall}` },
      { title: "服务端：和 sshd 放在一起", body: "隧道复用你已有的 SSH 密钥，白名单就是一个普通的 authorized_keys 文件。放行 UDP 7443，并记下它打印的 pin。", code: code.server, codeLabel: "shell" },
      { title: "客户端：~/.ssh/config 里加一行", body: "在原来的 Host 旁边新加一个别名，两个可以对比着用，随时能退回。先确认钥匙在 agent 里（ssh-add -l）。", code: code.client, codeLabel: "~/.ssh/config", after: "第一次连接时会打印一次服务端的 pin，就像 SSH 首次连接时的主机密钥确认。拿它和服务端打印的 pin 核对一下。" },
      { title: "亲眼看看", body: "关掉再打开 Wi-Fi、切到热点，或者合上盖子半分钟。时钟会停一下，再把错过的每一秒补上。", code: code.tryIt, codeLabel: "shell" },
    ],
    more: "团队、SSH CA、硬件钥匙、systemd 与排错：看迁移指南",
  },
  security: {
    title: "额外的一层，而不是替代",
    body: "sshd 照样认证你，SSH 照样端到端加密一切。想通过隧道，客户端要用服务端白名单里的钥匙签名。这个签名绑定在当前这条 TLS 连接上，既不能重放，也不能被挪用成 SSH 登录签名。线上不传任何秘密。撤销权限就是删一行，再发一个 SIGHUP。",
    link: "威胁模型与加固清单",
  },
  evidence: {
    title: "我们怎么知道它可靠",
    lead: "每次 push 都对着真实的 sshd 和真实的 OpenSSH 客户端跑，边界上不用任何 mock。",
    stats: [
      { value: "18", label: "个端到端用例", detail: "scp 完整性、销毁链路、30 秒网络黑洞、跳板机、凭据撤销" },
      { value: "17", label: "个日常 SSH 场景", detail: "pty、32 MiB 输出、全部 256 个字节值、-L/-R/-D、sftp、rsync、tmux" },
      { value: "7", label: "个漫游用例", detail: "用远端计数器测量；同一套用例能驱动真实的 Wi-Fi 网卡" },
    ],
    link: "阅读验证计划",
  },
  faq: {
    title: "常见问题",
    items: [
      { q: "断网时间超过 linger 会怎样？", a: "会话会被放弃，ssh 正常退出，和现在一样。断网经常更久的话，在两端都调大 --session-linger，再用 tmux 兜底。" },
      { q: "会让 SSH 变快吗？", a: "不会，这不是它的目标，它的目标是不断。性能相关的工作在路线图里。" },
      { q: "跑隧道的人能看到我的会话内容吗？", a: "看不到。隧道转发的是 SSH 协议本身，在你的 ssh 和 sshd 之间早就端到端加密了。" },
      { q: "sshd 看到的连接都来自 127.0.0.1，有影响吗？", a: "有：sshd 上的 from=\"...\" 限制，以及 fail2ban 这类按 IP 工作的工具都会受影响。隧道服务端的日志会记下每个会话属于哪把钥匙或哪台设备。见安全模型 R-1。" },
      { q: "能扛过服务器或笔记本重启吗？", a: "暂时不能，会话状态在内存里。跨进程持久化是路线图里的 M4，这种情况请用 tmux。" },
    ],
  },
  footer: { license: "MPL-2.0 许可", docs: "设计文档", madeWith: "只依赖 quic-go 和 golang.org/x/crypto。" },
  copy: { copy: "复制", copied: "已复制" },
};
